import React, { useState } from 'react';
import { AppFooter } from './LandingPage.jsx';

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h3 style={{ fontSize: 15, fontWeight: 700, color: 'var(--accent2)', marginBottom: 8 }}>{title}</h3>
      <p style={{ color: 'var(--text2)', fontSize: 14, lineHeight: 1.8 }}>{children}</p>
    </div>
  );
}

function TermsContent() {
  return <>
    <Section title="1. Acceptance of Terms">
      By accessing or using Erivion ("the Service", "the Platform"), you confirm that you are at least 13 years of age and agree to be legally bound by these Terms of Service. If you do not agree to these Terms, you must not use the Service. Continued use of the Service after any changes constitutes your acceptance of the revised Terms.
    </Section>
    <Section title="2. Description of Service">
      Erivion is an AI-powered video creation platform that allows users to generate videos from text ideas or scripts. The Service uses third-party AI and media providers including Groq, Pexels, Stability AI, and Seedance to deliver its functionality.
    </Section>
    <Section title="3. User Accounts">
      You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account. You must notify us immediately of any unauthorized use at digidelight33@gmail.com.
    </Section>
    <Section title="4. Acceptable Use & Prohibited Content">
      You agree not to use the Service to create, distribute, or promote content that: (a) is sexually explicit, pornographic, or adult in nature; (b) contains graphic violence, gore, or glorifies harm; (c) promotes hatred, discrimination, or violence based on race, religion, gender, nationality, sexual orientation, or disability; (d) facilitates illegal activities including fraud, piracy, or drug use; (e) constitutes misinformation, deepfakes intended to deceive, or impersonation; (f) involves or is directed at minors in an inappropriate or harmful manner; (g) infringes on third-party intellectual property rights. Violations will result in immediate account suspension or termination without refund.
    </Section>
    <Section title="5. Payments & Subscriptions">
      Paid plans are billed on a monthly or annual basis depending on the selected plan. For Egyptian users, subscriptions are activated manually after InstaPay payment verification. For international users, payments are processed via Gumroad which handles payment processing. International memberships renew automatically through Gumroad monthly unless cancelled.
    </Section>
    <Section title="6. Cancellation & Refund Policy">
      Users may request cancellation and a full refund within 4 hours of subscription activation, provided they have not created any videos using the plan. If videos have been created, a partial refund will be issued based on the value of unused credits/videos, deducting the cost of videos already generated. Refund requests must be submitted exclusively through the Support page on the platform. Refunds are processed within 24 hours of approval. After the 4-hour window, no refunds will be issued except in cases of technical failure on our end. Subscriptions are non-transferable and cannot be shared between accounts.
    </Section>
    <Section title="7. Advertising">
      Erivion does not display third-party advertisements. The platform is entirely ad-free. Your experience will never be interrupted by ads.
    </Section>
    <Section title="8. Intellectual Property">
      The Erivion platform, brand, and underlying technology are owned by Erivion and protected by intellectual property laws. Videos generated by users using their own original inputs are owned by the respective users, subject to these Terms and applicable law. Users grant Erivion a non-exclusive license to process submitted content solely for the purpose of delivering the Service.
    </Section>
    <Section title="9. Disclaimers & Limitation of Liability">
      The Service is provided "as is" without warranties of any kind. Erivion is not liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability to you shall not exceed the amounts you paid to Erivion in the 12 months preceding the claim.
    </Section>
    <Section title="10. Termination">
      Erivion reserves the right to suspend or terminate your account at any time for violation of these Terms, without prior notice. You may terminate your account by contacting us at digidelight33@gmail.com.
    </Section>
    <Section title="11. Governing Law">
      These Terms are governed by applicable law. Disputes shall be resolved through good-faith negotiation before any legal proceedings.
    </Section>
    <Section title="12. Changes to Terms">
      We may update these Terms at any time. We will notify users of significant changes via email or a prominent notice on the platform. Continued use after changes constitutes acceptance.
    </Section>
    <Section title="13. Contact Us">
      For any questions about these Terms, please contact us at digidelight33@gmail.com or through the Support page on the platform.
    </Section>
  </>;
}

function PrivacyContent() {
  return <>
    <Section title="1. Introduction">
      Erivion ("we", "us", "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our Service. By using Erivion, you consent to the practices described in this Policy. This policy is compliant with applicable privacy regulations including GDPR principles.
    </Section>
    <Section title="2. Information We Collect">
      We collect the following types of information: (a) Account Information — email address, name, and password when you register; (b) Profile Data — avatar and name from Google OAuth when you sign in with Google; (c) Usage Data — videos created, features used, credits consumed, and interaction logs; (d) Technical Data — IP address, browser type, device information, operating system, and referring URLs; (e) Payment Information — for Egyptian users, we store plan type and payment confirmation screenshots (we do not collect or store credit card numbers). For international users, payment processing is handled entirely by Gumroad and we do not store any payment card details.
    </Section>
    <Section title="3. How We Use Your Information">
      We use your information to: provide and maintain the Service; process account registration and authentication; send transactional emails such as verification codes and payment confirmations; monitor and enforce compliance with our Terms of Service; analyze usage patterns to improve the platform; and communicate important service updates.
    </Section>
    <Section title="4. Ad-Free Platform">
      Erivion is completely ad-free. We do not use Google AdSense or any other advertising network. We do not serve ads, track users for advertising purposes, or share your data with advertising companies.
    </Section>
    <Section title="5. Gumroad (International Payments)">
      For international users, payments are processed by Gumroad. Gumroad collects and processes payment information directly and is subject to their own Privacy Policy available at https://gumroad.com/privacy. We receive only transaction confirmation and subscription status from Gumroad — no card details are shared with us. Egyptian users pay via InstaPay, a local mobile payment service.
    </Section>
    <Section title="6. Cookies & Tracking Technologies">
      We use the following types of cookies and storage: (a) Essential cookies — for login session management and authentication tokens stored in localStorage; (b) Analytics cookies — to understand how users interact with the Service. You can control cookie preferences through your browser settings. Disabling essential cookies may affect Service functionality.
    </Section>
    <Section title="7. Third-Party Services">
      Erivion integrates with the following third-party services, each with their own privacy policies: Google OAuth — https://policies.google.com/privacy; Groq AI — https://groq.com/privacy; Pexels — https://www.pexels.com/privacy-policy; Stability AI — https://stability.ai/privacy-policy; Gumroad — https://gumroad.com/privacy. We are not responsible for the privacy practices of these third-party services.
    </Section>
    <Section title="8. Data Storage & Security">
      Your data is stored on secure servers. We implement industry-standard security measures including encryption of sensitive data and secure HTTPS connections. We do not sell, rent, or trade your personal information to third parties. Data is retained for as long as your account is active or as needed to provide the Service.
    </Section>
    <Section title="9. Children's Privacy">
      Erivion is not directed at children under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we will take steps to delete such information immediately.
    </Section>
    <Section title="10. Your Rights & Choices">
      You have the right to: access the personal data we hold about you; correct inaccurate data; request deletion of your account and associated data; and withdraw consent at any time. To exercise these rights, contact us at digidelight33@gmail.com. We will respond to your request within 30 days.
    </Section>
    <Section title="11. Data Transfers">
      Your information may be processed in countries other than your own. By using the Service, you consent to the transfer of your information to countries that may have different data protection laws than your country of residence.
    </Section>
    <Section title="12. Changes to This Policy">
      We may update this Privacy Policy from time to time. We will notify you of significant changes by posting a notice on our platform or by email. Your continued use of the Service after changes constitutes acceptance of the updated Policy.
    </Section>
    <Section title="13. Contact Us">
      If you have any questions or concerns about this Privacy Policy or our data practices, please contact us at: digidelight33@gmail.com or through the Support page on the platform.
    </Section>
  </>;
}

function RefundContent() {
  return <>
    <Section title="Overview">
      At Erivion, we want you to be satisfied with your subscription. This Refund & Cancellation Policy explains the conditions under which refunds are granted and how to request them.
    </Section>
    <Section title="Eligibility for Refund">
      You are eligible for a full refund if: (a) you request cancellation within 4 hours of subscription activation; AND (b) you have not created any videos using the activated plan during that period. If you have created videos during the 4-hour window, a partial refund will be issued. The refund amount will be calculated by deducting the cost of videos already generated from your total payment, and the remaining balance will be returned to you.
    </Section>
    <Section title="How Refunds Are Calculated">
      Each video type has a unit cost based on your subscription plan. The number of videos you created will be multiplied by their unit cost and deducted from your payment. The remaining amount will be refunded. For example: if you paid $20 and used videos worth $5, you will receive a $15 refund.
    </Section>
    <Section title="How to Request a Refund">
      All refund and cancellation requests must be submitted exclusively through the Support page on the Erivion platform. Requests sent via email or any other channel will not be processed. When submitting your request, please include: your account email address, the plan you wish to cancel, and the reason for cancellation. Our team will review your request and respond within 24 hours.
    </Section>
    <Section title="Refund Processing Time">
      Approved refunds are processed within 24 hours of approval. The time it takes for the funds to appear in your account depends on your payment method and bank, typically 3–10 business days for card payments.
    </Section>
    <Section title="Non-Refundable Situations">
      Refunds will not be issued in the following cases: (a) requests made more than 4 hours after subscription activation; (b) accounts suspended or terminated due to violations of our Terms of Service; (c) dissatisfaction with AI-generated content quality, as results vary based on your inputs; (d) failure to use the service during the subscription period.
    </Section>
    <Section title="Subscription Cancellation">
      Cancelling your subscription stops future renewals. Since Erivion does not use automatic recurring billing, your subscription will simply expire at the end of the current period without any further charges. You will retain access to your plan features until the expiration date.
    </Section>
    <Section title="International Users (Gumroad)">
      For users who paid via Gumroad, the same refund eligibility conditions apply. Please submit your request through the Support page within 4 hours of your subscription being activated. We will handle the refund coordination with Gumroad on your behalf.
    </Section>
    <Section title="Contact">
      For all refund and cancellation requests, use the Support page on the platform. For urgent matters, you may also reach us at digidelight33@gmail.com.
    </Section>
  </>;
}

function AboutContent() {
  return <>
    <Section title="Our Mission">To make professional video creation accessible to everyone — no expensive software or editing experience required.</Section>
    <Section title="What We Do">Erivion is an AI-powered video generation platform. Provide an idea or script, and we handle scenes, footage, voiceovers, captions, music, and effects.</Section>
    <Section title="Our Technology">State-of-the-art language models for scripting, neural text-to-speech for voiceovers, and a professional rendering pipeline built on FFmpeg. Supporting 8+ languages.</Section>
    <Section title="Content Standards">We strictly prohibit harmful, explicit, or misleading content with automated and manual review mechanisms.</Section>
    <Section title="Contact">digidelight33@gmail.com — we read every message.</Section>
  </>;
}

function SupportContent() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [status, setStatus] = useState('idle');

  const handleSend = async () => {
    if (!email || !message) return;
    setStatus('loading');
    try {
      const res = await fetch('/api/auth/support', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, email, message }),
      });
      setStatus(res.ok ? 'sent' : 'error');
    } catch { setStatus('error'); }
  };

  if (status === 'sent') return (
    <div style={{ textAlign: 'center', padding: '40px 0' }}>
      <div style={{ fontSize: 52, marginBottom: 16 }}>✅</div>
      <h3 style={{ fontSize: 20, fontWeight: 700, color: 'var(--green)', marginBottom: 8 }}>Message Sent!</h3>
      <p style={{ color: 'var(--text3)' }}>We'll get back to you within 24 hours.</p>
    </div>
  );

  return (
    <div>
      <div style={{ background: 'rgba(124,106,247,0.08)', border: '1px solid rgba(124,106,247,0.2)', borderRadius: 12, padding: '14px 18px', marginBottom: 24 }}>
        <p style={{ color: '#7c6af7', fontWeight: 600, fontSize: 14, margin: '0 0 6px' }}>💡 Refund & Cancellation Requests</p>
        <p style={{ color: 'var(--text2)', fontSize: 13, margin: 0, lineHeight: 1.6 }}>
          If you'd like to cancel your subscription or request a refund, please use this form. Include your account email and plan details. Refund requests are only accepted within 4 hours of activation. See our <strong>Refund Policy</strong> for full details.
        </p>
      </div>
      <p style={{ color: 'var(--text2)', fontSize: 14, lineHeight: 1.7, marginBottom: 28 }}>
        Having trouble? Fill out the form below or email us directly at{' '}
        <a href="mailto:digidelight33@gmail.com" style={{ color: 'var(--accent2)' }}>digidelight33@gmail.com</a>
      </p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        <input placeholder="Your name" value={name} onChange={e => setName(e.target.value)}
          style={{ padding: '12px 14px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--bg2)', color: 'var(--text)', fontSize: 14, outline: 'none' }} />
        <input type="email" placeholder="Your email *" value={email} onChange={e => setEmail(e.target.value)}
          style={{ padding: '12px 14px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--bg2)', color: 'var(--text)', fontSize: 14, outline: 'none' }} />
        <textarea placeholder="Describe your issue or refund request *" value={message} onChange={e => setMessage(e.target.value)} rows={5}
          style={{ padding: '12px 14px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--bg2)', color: 'var(--text)', fontSize: 14, outline: 'none', resize: 'vertical', fontFamily: 'inherit' }} />
        {status === 'error' && <p style={{ color: 'var(--red)', fontSize: 13 }}>Something went wrong. Please email us directly.</p>}
        <button onClick={handleSend} disabled={!email || !message || status === 'loading'}
          style={{ padding: '12px 24px', background: 'var(--accent)', color: '#fff', border: 'none', borderRadius: 10, fontWeight: 700, fontSize: 14, cursor: (!email || !message) ? 'not-allowed' : 'pointer', opacity: (!email || !message) ? 0.6 : 1, alignSelf: 'flex-start' }}>
          {status === 'loading' ? '⏳ Sending...' : 'Send Message →'}
        </button>
      </div>
    </div>
  );
}

const PAGE_CONFIG = {
  terms:   { title: 'Terms of Service',        icon: '📄' },
  privacy: { title: 'Privacy Policy',           icon: '🔒' },
  refund:  { title: 'Refund & Cancellation',    icon: '💰' },
  about:   { title: 'About Erivion',            icon: 'ℹ️' },
  support: { title: 'Support',                  icon: '🛟' },
};

export default function SubPage({ page, onBack }) {
  const config = PAGE_CONFIG[page] || { title: page, icon: '📄' };

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', padding: '40px 20px 80px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        <button onClick={onBack} style={{ display: 'flex', alignItems: 'center', gap: 8, background: 'transparent', border: 'none', color: 'var(--text3)', cursor: 'pointer', fontSize: 14, marginBottom: 32, padding: 0 }}>
          ← Back
        </button>
        <h1 style={{ fontSize: 30, fontWeight: 800, marginBottom: 36, letterSpacing: '-0.5px', color: 'var(--text)' }}>
          {config.icon} {config.title}
        </h1>
        {page === 'terms'   && <TermsContent />}
        {page === 'privacy' && <PrivacyContent />}
        {page === 'refund'  && <RefundContent />}
        {page === 'about'   && <AboutContent />}
        {page === 'support' && <SupportContent />}
      </div>
    </div>
  );
}